### ISSUE TITLE
Unlock connector buttons should be disabled if the connector status is ‘Available’

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-mobile#175]
Unlock connector buttons should be disabled if the connector status is ‘Available’
Avoid generic message ‘Request has failed’ but rather ‘Cannot unlock the connector’ (to be checked everywhere)
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/2c9259a1-e135-4a8a-8f1f-e6eca7184528)

**Comment by LucasBrazi06** [comment]
@fcoutellier 
Just deployed the version 1.3.5 Beta on both stores
