### ISSUE TITLE
Mobile curve problem

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-mobile#205]
This issue has been reported (by Flo) while starting a new charging session on the mobile application.

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/d87fefd5-badf-4354-b4db-bdc13059a458)

**Comment by fcoutellier** [comment]
![image](https://user-images.githubusercontent.com/7858535/86104476-5cb2dd80-babe-11ea-81ff-4059ecd1f78a.png)

Issue occurs when 

plugins the car
Starting the session from the e-mobility
The session charge in the car is delay (like to start at 11pm)

The strange curve above with 0.1kw is displayed in the dashboard but in the mobile app the curve is definitely wrong...

**Comment by LucasBrazi06** [comment]
> The strange curve above with 0.1kw is displayed in the dashboard but in the mobile app the curve is definitely wrong...

Ok, thanks Fred for the investigation, I will have a look !

**Comment by LucasBrazi06** [comment]
Session ID 1575761707 in charge@home

**Comment by LucasBrazi06** [comment]
Fixed

**Comment by fcoutellier** [comment]
Issue seems not reproducible any longer.
