### ISSUE TITLE
Mobile - Charging Station in error push button

### ISSUE THREAD

**Issue by fcoutellier** [LucasBrazi06/ev-mobile#206]
An End-User should be able to push the information that a charging station is in error (charging scenario is failing)

- [ ] Create a new button -> Side bar 

<b>The screen must have displayed:</b>
  - [ ] First Name - mandatory (*)
  - [ ] Last Name - mandatory (*)
  - [ ] e-mail - mandatory (*)
  - [ ] Phone number - mandatory (*)
  - [ ] A text field with the description of the problem - mandatory (*)

A button on the mobile application should be built here.

The backend call will be done in the issue 1679 by Tobias.

![image](https://user-images.githubusercontent.com/7858535/87770131-e1bc2780-c81e-11ea-962f-109e9d592e93.png)

**Comment by fcoutellier** [comment]
![image](https://user-images.githubusercontent.com/7858535/87554275-38592280-c6b4-11ea-8b45-2ef6199b32df.png)

**Comment by fcoutellier** [comment]
Here is a sample from a competitor:

![IMG_3807](https://user-images.githubusercontent.com/7858535/87767307-c0f1d300-c81a-11ea-9818-5a7d6029ac7a.PNG)
![IMG_3805](https://user-images.githubusercontent.com/7858535/87767317-c3ecc380-c81a-11ea-8839-ff856074a8ba.PNG)

**Comment by LucasBrazi06** [comment]
Redesign the screen ReportError + Theme

**Comment by LucasBrazi06** [comment]
Dups of #31
