### ISSUE TITLE
Mobile - Charging plans management

### ISSUE THREAD

**Issue by yannpub** [LucasBrazi06/ev-mobile#227]
_Enhancement proposal_
Would be nice if there would be a way to temporarily de-activate the charging plan from the mobile device. 

_Case Scenario:_
You have setup a recurrent charging plan, in order to use off-peak hours. However you need to have an immediate charge during peak hours. You can't de-activate your charging plan from the mobile device, you have to go through the web app.

**Comment by LucasBrazi06** [comment]
Thanks for your feedback,
We already planned that, we just need ressources and time :-)
