### ISSUE TITLE
Mobile: Upgrade to new version of react-native navigation

### ISSUE THREAD

**Issue by Skyrix06** [LucasBrazi06/ev-mobile#236]

**Comment by Skyrix06** [comment]
- [ ]  fix the navigation towards the connector details screen
- [ ]  fix the auto login
- [ ]  save the last used screen

**Comment by Skyrix06** [comment]
Try to finish this week

**Comment by Skyrix06** [comment]
normally finished on tomorrow or Wednesday

**Comment by Skyrix06** [comment]
Fix to do for now:

- [ ] Charging Station list exceed on the header (only on IOS)
- [ ] Can't remove the Charging Station Detail connector modal when you click on a map pin (only on IOS)

**Comment by Skyrix06** [comment]
Was a problem on the emulator, everything work fine on IOS and android

**Comment by LucasBrazi06** [comment]
Tested Ok
