### ISSUE TITLE
Scan & Charge: Scan a QR Code on a charger + Start charging right away

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-mobile#32]

**Comment by Skyrix06** [comment]
- [x]  Create the QR Code Button on the Login and Home screen
- [x]  Check the QR Code information
- [x]  Handle the Navigation to the charging Station when QR Code scan
- [ ]  Add the tenant automatically when the user scan the QR Code on the Login screen.
- [ ]  Ask the user to change the tenant if he want to access to a Charging Station in the wrong tenant

**Comment by Skyrix06** [comment]
Data syntax exemple:

{"tenantSubDomain":"slf", "tenantName":"SAP Labs France (prod)", "endpoint":"scp", "chargingStationID":"SAP-Mougins-18", "connectorID":2}

**Comment by WillyLellouch** [comment]
Gerald has tested and validated the good function of the feature
